### ISSUE TITLE
kanban board review

### ISSUE THREAD

**Issue by mohamed20163858** [mohamed20163858/spacex-traveles-hub#21]
https://github.com/users/mohamed20163858/projects/4
note: i am the only one  in this group project read this message from microverse success team please: - 
  
Kiana Anderson (Microverse)Oct 18, 2022, 19:24 GMT+2Hi Mohamed, Alaa has been granted the appeal so they will no longer be your partner. Unfortunately, we were not able to repair you with new partners so you will remain solo for the rest of the week.  We understand that working alone can be a little challenging, but thankfully our weeks are designed so that you can complete the activities alone. For technical projects or professional skill projects that specifically require input from another person, please reach out to your Standup Team to ask for help. If needed, complete the task alone to the best of your ability. If you feel blocked, reach out to us as soon as possible in order for us to help you while working alone. Your Standup team is another great resource that you can rely on if you have questions.

**Comment by sja-thedude** [comment]
Hi, I have sent a message on slack. Could you reply there?

**Comment by sja-thedude** [comment]
## Required Changes ♻️

Hi @mohamed20163858, This is @sja-thedude your code reviewer.

Good job so far!
There are some issues that you still need to work on to go to start the project but you are almost there!

![768070f3-bc9a-4aba-b8bc-25793e00ea1e_text](https://user-images.githubusercontent.com/70269507/159483175-2f61461d-b352-4cb4-98f8-b173e05ab5ff.gif)

## Highlights
✔️ Good job so far

## Required 
- [x] Kindly make sure that the cards are equal to 17. Currently, your cards are 13.

Note: @mohamed20163858 is the only person to work on this group project and he has got a message from student success for that.
![image](https://user-images.githubusercontent.com/70269507/196558321-c6932257-a66c-4d3c-a34b-9c384189eec2.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mohamed20163858** [comment]
thanks a lot the problem is resolved

**Comment by Reem-lab** [comment]
# Hi @mohamed20163858,👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉🔥🔥💯💯
<img src="https://media3.giphy.com/media/3oz8xAFtqoOUUrsh7W/giphy.gif"/>

## Highlights ✨✨
📌 Descriptive pull request✅
📌 Great working on the set up✅
📌 Good commit messages ✅


## Optional suggestions


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
